apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: simpleapp-ingress
  namespace: prova
spec:
  rules:
  - host: app.prova
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: simpleapp-svc
            port:
              number: 80
  